[package]
name = "slime_mold"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.25"
rand = "0.8.5"
rayon = "1.6.1"
num_cpus = "1.15.0"